url: https://willarchercreative.com
collections:
  projects:
    output: true
    permalink: :title/

defaults:
  -
    scope:
      path: ""
      type: "projects"
    values:
      nav-color: "nbar-light"